# Generated by Django 4.2.3 on 2023-07-21 13:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "participants",
                    models.ManyToManyField(
                        related_name="team", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Work", "Work"),
                            ("Finished", "Finished"),
                            ("Canceled", "Canceled"),
                        ],
                        default="Work",
                        max_length=10,
                    ),
                ),
                (
                    "team",
                    models.ManyToManyField(related_name="project", to="task.team"),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
